# Generated by Django 3.0.11 on 2020-12-30 09:31

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default={'djinni': '', 'dou': '', 'rabota': '', 'work': ''})),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.City')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Language')),
            ],
            options={
                'unique_together': {('city', 'language')},
            },
        ),
    ]
